PNaCl: Fix ambiguity in reference to PassManager
In LLVM 3.4, PassManager is defined by "using legacy::PassManager", so
forward-declaring it no longer works.  When compiling with Clang 3.4
(for the sandboxed translator), it gave this error:

include/llvm/Transforms/NaCl.h:54:38: error: reference to 'PassManager' is ambiguous
void PNaClABISimplifyAddPreOptPasses(PassManager &PM);
include/llvm/Transforms/NaCl.h:21:7: note: candidate found by name lookup is 'llvm::PassManager'
class PassManager;
include/llvm/PassManager.h:34:15: note: candidate found by name lookup is 'llvm::PassManager'
using legacy::PassManager;

(However, gcc 4.6.3 didn't complain.)

Fix this by using PassManagerBase in the same way that addPass() in
opt.cpp does.

BUG=https://code.google.com/p/nativeclient/issues/detail?id=3757
TEST=tested with LLVM 3.4 merged
R=jvoung@chromium.org

Review URL: https://codereview.chromium.org/143853002