PNaCl: Fix mistake in flatten-globals.ll test
The mistake meant that this CHECK line wasn't being checked.

In LLVM 3.4, lit got stricter so that it caught this mistake, with the
error:

  error: no check strings found with prefix 'CLEANED:'

BUG=https://code.google.com/p/nativeclient/issues/detail?id=3757
TEST=tested with LLVM 3.4 merged
R=jvoung@chromium.org

Review URL: https://codereview.chromium.org/143863002